### ISSUE TITLE
Warnings during build, ReferenceError during Runtime

### ISSUE THREAD

**Issue by thompcd** [exybore/svelteify#3]
I installed the package using: `npm i --dev sveltify` without issue.

With a lack of documentation, I saw the tests and attempted to use the MAvatar test as an example of how to use a component.

I added the following code to attempt to use:

```
<script>
import {MAvatar} from '@sveltify';
let props;
</script>

<MAvatar {...props}>
  <img
    alt="Avatar"
    src="https://avatars0.githubusercontent.com/u/12774204?s=460&v=4"
  />
</MAvatar>
```
During compile, I received the following warnings:

> (!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@sveltify (imported by src/App.svelte)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
@sveltify (guessing '_sveltify')

I'm assuming this is due to an incomplete installation, but that's pure speculation, I just wanted to make sure this was reported.

In my live-server, I receive the following error in the console:

> ReferenceError: _sveltify is not defined

**Comment by exybore** [comment]
You didn't installed the correct library : it's `svelteify`, not `sveltify` 😅
